### ISSUE TITLE
add dependency to auto-complete?

### ISSUE THREAD

**Issue by kristianlm** [chicken-contrib/chicken-scheme.el#1]
I installed chicken-scheme from package-list-packages, without auto-complete installed, and got this:

```
Compiling no file at Fri Nov 23 11:14:20 2012
Leaving directory `/home/klm/.emacs.d/elpa/chicken-scheme-1.0.0'

Compiling file /home/klm/.emacs.d/elpa/chicken-scheme-1.0.0/chicken-scheme-pkg.el at Fri Nov 23 11:14:20 2012
Entering directory `/home/klm/.emacs.d/elpa/chicken-scheme-1.0.0/'

Compiling file /home/klm/.emacs.d/elpa/chicken-scheme-1.0.0/chicken-scheme.el at Fri Nov 23 11:14:20 2012
chicken-scheme.el:49:1:Error: Cannot open load file: auto-complete

```

I maunally installed auto-complete and got passed that error. Is it possible to add auto-complete to chicken-scheme's dependencies so this gets installed automatically?

**Comment by dleslie** [comment]
Very odd. At the top of the file is (require 'auto-complete), package.el should have stripped that out and listed it as a dependency.

What version of Emacs are you running?

**Comment by kristianlm** [comment]
I'm on `GNU Emacs 24.2.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.6.1) of 2012-11-03`
